In [12]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
import numpy as np

In [14]:
scores = np.array([
    [85, 90, 78, 92, 88],  # Student 1
    [72, 75, 80, 68, 74],  # Student 2
    [95, 88, 92, 96, 90],  # Student 3
    [60, 65, 70, 58, 62],  # Student 4
    [88, 84, 86, 89, 87]   # Student 5
])

In [16]:
# 1. Retrieve the scores of Student 3 for all subjects
student_3_scores = scores[2]
print(f"Student 3's scores: {student_3_scores}")

Student 3's scores: [95 88 92 96 90]


In [17]:
# 2. Retrieve the scores for Subject 2 (column 2) across all students
subject_2_scores = scores[:, 1]
print(f"Scores for Subject 2 across all students: {subject_2_scores}")

Scores for Subject 2 across all students: [90 75 88 65 84]


In [18]:
# 3. Extract the scores of the first 3 students for the first 2 subjects
first_3_students_first_2_subjects = scores[:3, :2]
print(f"First 3 students' scores for first 2 subjects: \n{first_3_students_first_2_subjects}")

First 3 students' scores for first 2 subjects: 
[[85 90]
 [72 75]
 [95 88]]


In [19]:
# 4. Extract the scores of the last 2 students for the last 3 subjects
last_2_students_last_3_subjects = scores[3:, -3:]
print(f"Last 2 students' scores for last 3 subjects: \n{last_2_students_last_3_subjects}")

Last 2 students' scores for last 3 subjects: 
[[70 58 62]
 [86 89 87]]


In [20]:
# 5. Add 5 bonus marks to all scores
scores_with_bonus = scores + 5
print(f"Scores with bonus marks: \n{scores_with_bonus}")

Scores with bonus marks: 
[[ 90  95  83  97  93]
 [ 77  80  85  73  79]
 [100  93  97 101  95]
 [ 65  70  75  63  67]
 [ 93  89  91  94  92]]


In [21]:
# 6. Subtract 10 marks from scores of Subject 4 for all students
scores_with_bonus[:, 3] -= 10
print(f"Scores with 10 marks subtracted from Subject 4: \n{scores_with_bonus}")

Scores with 10 marks subtracted from Subject 4: 
[[ 90  95  83  87  93]
 [ 77  80  85  63  79]
 [100  93  97  91  95]
 [ 65  70  75  53  67]
 [ 93  89  91  84  92]]


In [22]:
# 7. Calculate the percentage scores of each student assuming each subject is out of 100
percentages = np.sum(scores, axis=1) / (scores.shape[1] * 100) * 100
print(f"Percentage scores for each student: {percentages}")

Percentage scores for each student: [86.6 73.8 92.2 63.  86.8]


In [23]:
# 8. Calculate the average score for each student across all subjects
average_scores_per_student = np.mean(scores, axis=1)
print(f"Average score for each student: {average_scores_per_student}")

Average score for each student: [86.6 73.8 92.2 63.  86.8]


In [24]:
# 9. Find the total marks scored by each student
total_marks_per_student = np.sum(scores, axis=1)
print(f"Total marks scored by each student: {total_marks_per_student}")

Total marks scored by each student: [433 369 461 315 434]


In [25]:
# 10. Identify the highest score in the entire array
highest_score = np.max(scores)
print(f"Highest score in the entire array: {highest_score}")

Highest score in the entire array: 96


In [26]:
# 11. Determine the average score for each subject
average_scores_per_subject = np.mean(scores, axis=0)
print(f"Average score for each subject: {average_scores_per_subject}")

Average score for each subject: [80.  80.4 81.2 80.6 80.2]


In [27]:
# 12. Find the student with the lowest average score
lowest_avg_score_student = np.argmin(average_scores_per_student)
print(f"Student with the lowest average score: Student {lowest_avg_score_student + 1}")

Student with the lowest average score: Student 4
