In [1]:
pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip



   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 1.4 MB/s eta 0:00:09
   -- ------------------------------------- 0.8/12.6 MB 1.3 MB/s eta 0:00:09
   -- ------------------------------------- 0.8/12.6 MB 1.3 MB/s eta 0:00:09
   --- ------------------------------------ 1.0/12.6 MB 867.9 kB/s eta 0:00:14
   ---- ----------------------------------- 1.3/12.6 MB 910.8 kB/s eta 0:00:13
   ----- ---------------------------------- 1.8/12.6 MB 1.1 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/12.6 MB 1.1 MB/s eta 0:00:10
   ------- -------------------------------- 2.4/12.6 MB 1.2 MB/s eta 0:00:09
   --------- ------------------------------ 2.9/12.6 MB 1.3 MB/s eta 0:00:08
   ---------- ----------------------------- 3.4/12.6 MB 1.4 MB/s eta 0:00:07
   ------------

In [2]:
import numpy as np

In [3]:
sales = np.array([100, 200, 150, 300, 250, 400, 350])
print(sales)

[100 200 150 300 250 400 350]


In [4]:
prices_store_1 = np.array([10, 20, 30])
prices_store_2 = np.array([1, 2, 3])
result = prices_store_1 * prices_store_2
print(result)

[10 40 90]


In [5]:
sales_january = np.array([300, 400])
sales_february = np.array([500, 600])
combined_sales = np.concatenate((sales_january, sales_february))
print(combined_sales)

[300 400 500 600]


In [6]:
scores = np.array([[80, 90], [85, 95]])
flattened_scores = scores.flatten()
print(flattened_scores)

[80 90 85 95]


In [7]:
data = np.array([1, 2, 3, 4, 5, 6])
reshaped_data = data.reshape(2, 3)
print(reshaped_data)


[[1 2 3]
 [4 5 6]]
